apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
      app: myapp
      type: front-end
# 4 section, that define template for the replicaset
spec:
  template:
    metadata:
     name: myapp-pod
     labels: #dic key:value
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx

  replicas: 3
  selector:
     matchLabels:
        type: front-end

# k create -f deployment-definition.yml