# 1st section Replication Controller
apiVersion: v1
# 2 section
kind: ReplicationController
# 3 section
metadata:
  name: myapp-rc
  labels:
      app: myapp
      type: front-end
# 4 section, that define tample for the replicaset
spec:
  template:
    metadata:
     name: myapp-pod
     labels: #dic key:value
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx

  replicas: 3